development:
  adapter: mysql2
  database: bicing_stats_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: bicing_stats_production
  username: bicing_stats

